import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const TRANSLATIONS = {
  en: {
    common: {
      prakasamPolice: "Prakasam Police",
      citizenPortal: "Citizen Portal",
      officialCitizenPortal: "Official Citizen Portal",
      navigation: "Navigation",
      live: "Live",
      loading: "Loading...",
      unauthorized: "Access Denied",
      unauthorizedDesc: "You don't have permission to access this page.",
      goBack: "Go Back",
      submit: "Submit",
      submitting: "Submitting...",
      cancel: "Cancel",
      close: "Close",
      yes: "Yes",
      no: "No",
    },
    navbar: {
      home: "Home",
      emergencyServices: "Emergency Services",
      knowYourRights: "Know Your Rights",
      myPortal: "My Portal",
      signIn: "Sign In",
      logout: "Logout",
      citizen: "Citizen",
      admin: "Admin",
      clickToLogout: "Click to logout",
      liveConnected: "Live Connected",
      disconnected: "Disconnected",
      activeEscalations: "active escalations",
    },
    hero: {
      heading: "Don't Be Afraid to Report. Your Voice Can Save Lives.",
      subheading: "Stay calm. Don't panic. If you witness an accident, crime, fire, medical emergency, or suspicious activity, report the incident without fear. Your timely action can help save lives, protect families, and strengthen our community. Every responsible report makes our society safer.",
      reportBtn: "Report The Incident",
      learnBtn: "Learn How It Works",
      quote1: "EVERY SECOND SAVES A LIFE.",
      quote2: "TOGETHER FOR A SAFER TOMORROW.",
      quote3: "YOUR SAFETY IS OUR PRIORITY.",
      quote4: "FASTER RESPONSE. STRONGER PROTECTION.",
      weListen: "We Listen. We Respond. We Protect.",
    },
    cards: {
      emergencyAssistance: "24×7 Emergency Assistance",
      emergencyAssistanceDesc: "Immediate routing to Police, Ambulance, or Fire dispatch.",
      secureReporting: "Safe & Secure Reporting",
      secureReportingDesc: "Encrypted connection keeping submissions highly secure.",
      quickPoliceResponse: "Quick Police Response",
      quickPoliceResponseDesc: "Automatic routing to the nearest active patrol units.",
      trackReport: "Your Privacy Matters",
      trackReportDesc: "Aligned with Digital Personal Data Protection Act safeguards.",
      aiIncidentAnalysis: "AI Incident Analysis",
      aiIncidentAnalysisDesc: "AI automatically analyzes emergency reports and prioritizes critical incidents for faster response.",
      liveEmergencyUpdates: "Live Emergency Updates",
      liveEmergencyUpdatesDesc: "Receive real-time notifications and status updates for your reported incidents.",
    },
    fearSection: {
      heading: "Report Without Fear",
      sub: "Every citizen has the right to report emergencies safely and confidently.",
      card1Title: "Your Identity Matters",
      card1Desc: "Your personal information is handled securely and shared only with authorized officials when required by law.",
      card2Title: "Every Report Counts",
      card2Desc: "Even small observations can help prevent larger incidents and improve public safety in our communities.",
      card3Title: "We Respect Your Privacy",
      card3Desc: "Emergency reports are processed using secure systems with appropriate role-based access controls.",
      card4Title: "Safer Communities Together",
      card4Desc: "Prompt reporting helps emergency responders reach people faster and protect the vulnerable.",
    },
    rightsSection: {
      heading: "Know Your Rights & Responsibilities",
      sub: "Understanding your rights and acting responsibly helps create a safer and more secure community for everyone.",
      disclaimer: "Disclaimer: This information is provided for civic awareness and does not constitute formal legal advice.",
      item1Title: "Right to Emergency Assistance",
      item1Desc: "Every citizen has the right to seek emergency assistance through India's emergency response services.",
      item2Title: "Right to Information",
      item2Desc: "Citizens have the right to obtain information from public authorities under the Right to Information Act, 2005, subject to applicable legal provisions.",
      item3Title: "Right to Privacy",
      item3Desc: "Your personal information is handled securely and accessed only by authorized officials when required for emergency response.",
      item4Title: "Responsible Reporting",
      item4Desc: "Providing accurate information helps emergency responders act quickly and protects the community.",
      item5Title: "Digital Evidence Awareness",
      item5Desc: "Photos, videos, voice recordings, and location details submitted during an incident may assist authorized investigations.",
      item6Title: "Community Responsibility",
      item6Desc: "Reporting emergencies promptly contributes to a safer society and faster assistance for those in need.",
    },
    login: {
      loginTitle: "Prakasam Police Portal",
      loginSub: "Enter credentials to access citizen portal",
      registerTitle: "Create Citizen Account",
      registerSub: "Sign up to report emergencies and track dispatch",
      fullName: "Full Name",
      fullNamePlaceholder: "Enter your full name",
      email: "Email Address",
      emailPlaceholder: "name@example.com",
      password: "Password",
      passwordPlaceholder: "••••••••",
      confirmPassword: "Confirm Password",
      confirmPasswordPlaceholder: "••••••••",
      phone: "Phone Number (Optional)",
      phonePlaceholder: "Enter 10-digit mobile number",
      signInBtn: "Sign In to Portal",
      signUpBtn: "Create Citizen Account",
      signingIn: "Signing In...",
      creatingAccount: "Creating Account...",
      needAccount: "Don't have an account?",
      registerLink: "Register here",
      haveAccount: "Already have an account?",
      loginLink: "Login here",
      errorDeny: "Access Denied: Only citizens can log in to this portal.",
      errorMatch: "Passwords do not match.",
      errorLength: "Password must be at least 6 characters.",
      errorRegister: "Registration failed. Email may already be in use.",
      welcomeBack: "Welcome back",
      welcome: "Welcome",
      accountCreated: "Account created.",
      invalidCreds: "Invalid email or password. Please try again.",
      quickDemoLogin: "Quick Demo Login",
      useDemoAccount: "Use Demo Citizen Account",
      demoPasswordLabel: "Demo password",
      backToHome: "Back to Home",
    },
    portal: {
      reportTitle: "Report Emergency Incident",
      reportSub: "Provide details of the emergency to alert dispatchers",
      incidentTitleLabel: "Incident Title",
      incidentTitlePlaceholder: "Briefly describe the emergency (e.g., Car accident at highway crossroads)",
      descriptionLabel: "Incident Description",
      descriptionPlaceholder: "Provide any details that can help responders (e.g., number of people involved, injuries, danger level)",
      typeLabel: "Incident Category",
      typePlaceholder: "-- Select Incident Type --",
      weaponLabel: "Weapon Involved?",
      peopleLabel: "Estimated People Affected",
      locationLabel: "Incident Location",
      locationPlaceholder: "Select location on map or use GPS",
      gpsBtn: "Use Current GPS Location",
      gpsSearching: "Locating device GPS...",
      gpsError: "Unable to retrieve GPS. Please pick a location manually.",
      successTitle: "Incident Report Submitted Successfully! 🚨",
      successDesc: "Your report has been received by Prakasam Police Dispatch. Tracking has initiated.",
      successNotice: "Dispatcher Review In-Progress. Keep your line open.",
      incidentId: "Incident ID",
      assignedUnit: "Assigned Unit",
      awaitingDispatch: "Awaiting Dispatch",
      activePatrol: "🚔 Unit",
      priorityLabel: "Priority Level",
      statusLabel: "Current Status",
      viewDashboard: "Go to Incident Dashboard",
      submitIncidentBtn: "Submit Emergency Report",
      validationTitle: "Please fill in all required fields.",
      validationLocation: "Please select a location on the map.",
      submitError: "Failed to submit report. Please try again.",
      fetchingAddress: "Fetching address...",
      step1: "Incident Details",
      step2: "Location Verification",
      gpsUnsupported: "Geolocation is not supported by your browser.",
      gpsCaptured: "GPS Location Captured",
      gpsDenied: "Location permission denied. Please allow access in browser settings or pin manually.",
      gpsTimeout: "GPS timed out. Please pin your location manually.",
      gpsPinHint: "Please pin your location on the map.",
      incidentSummary: "Incident Summary",
      priorityScore: "Priority Score",
      p1AutoDispatched: "P1 Critical — Response Unit auto-dispatched!",
      reportAnother: "Report Another",
      trackStatus: "Track Status",
      refetchGps: "Refetch GPS",
      retryGps: "Retry GPS",
      stepCategory: "Incident Type",
      stepDescribe: "Incident Details",
      stepLocation: "Pin Location",
      gpsObtaining: "Obtaining high-precision GPS coordinates…",
      emergencyDispatchGrid: "Emergency Dispatch Grid",
      reportDescText: "Your report will be automatically geocoded, triaged by AI priority scoring, and routed to the nearest response team.",
      gpsInstructions: "Your device GPS coordinates will load automatically. You can click on the map to manually move the response pin.",
      btnNextDetails: "Next: Describe Details →",
      btnNextLocation: "Next: Pin Location →",
    },
    myIncidents: {
      myIncidentsTitle: "My Emergency Reports",
      incDashboard: "Incident Dashboard",
      trackLive: "Track the live dispatch status of your submitted emergency reports.",
      failedLoad: "Failed to load your reports",
      noReports: "No Reports Registered",
      noReportsDesc: "You have not registered any emergency reports from this citizen account yet.",
      assignedUnitLabel: "Assigned unit",
      statusLabelCaps: "STATUS",
      locationLabelCaps: "LOCATION",
    },
    types: {
      assault: "Assault",
      robbery: "Robbery",
      shooting: "Shooting",
      accident: "Accident",
      fire: "Fire",
      medical: "Medical",
      domestic_violence: "Domestic Violence",
      theft: "Theft",
      vandalism: "Vandalism",
      suspicious: "Suspicious",
      noise: "Noise",
      other: "Other",
    },
    typesDesc: {
      assault: "Physical attack on a person",
      robbery: "Theft with force or threat",
      shooting: "Gunfire or gunshot wounds",
      accident: "Vehicle crash or collision",
      fire: "Building or vehicle fire",
      medical: "Medical emergency",
      domestic_violence: "Domestic abuse",
      theft: "Stolen property",
      vandalism: "Property damage",
      suspicious: "Suspicious activity",
      noise: "Noise disturbance",
      other: "Other emergency",
    },
    status: {
      pending: "Pending",
      dispatched: "Dispatched",
      en_route: "En Route",
      resolved: "Resolved",
    },
    priority: {
      P1: "P1 (Critical)",
      P2: "P2 (High)",
      P3: "P3 (Medium)",
      P4: "P4 (Low)",
    },
    footer: {
      helplines: "Official Emergency Services & Helplines",
      safetyGuidelines: "Citizen Safety Guidelines",
      disclaimerText: "This portal is a mock environment developed for demonstration purposes under public safety dispatch simulation.",
    },
    services: {
      nationalHelpline: "National Helpline (ERSS)",
      nationalHelplineDesc: "Unified emergency response system for all crises",
      policeControl: "Police Control Room",
      policeControlDesc: "Direct routing to state police dispatch centers",
      fireRescue: "Fire & Rescue Services",
      fireRescueDesc: "Fire combat, hazard mitigation, and rescue ops",
      medicalAssistance: "Ambulance / Medical Assistance",
      medicalAssistanceDesc: "Immediate medical transport and ambulance routing",
      womenHelpline: "Women Helpline",
      womenHelplineDesc: "Safety support for harassment and abuse cases",
    },
    safety: {
      tip1Title: "Stay Calm and Assess",
      tip1Text: "Take a deep breath. Assess your immediate surroundings for safety before filing any report.",
      tip2Title: "Share Accurate Location Details",
      tip2Text: "Point your location clearly on the map. Landmarks or street names help dispatchers route responders faster.",
      tip3Title: "Preserve Digital Evidence",
      tip3Text: "Only take photos or upload videos if you can do so safely without attracting attention or putting yourself in danger.",
      tip4Title: "Cooperate with Responding Officers",
      tip4Text: "Be ready to share details. Keep your phone line free in case dispatchers call you back for additional inputs.",
      tip5Title: "Avoid False Reports",
      tip5Text: "Filing false reports delays assistance for actual crises. Ensure all submissions are authentic and truthful.",
    },
    categories: {
      crimeTitle: "Crime",
      crimeDesc: "Theft, assault, robbery, trespass or active property hazard",
      crimeAction: "Report any unlawful activities immediately. Keep distance from suspects.",
      medicalTitle: "Medical Emergency",
      medicalDesc: "Critical health crisis, accidents, or urgent medical transport",
      medicalAction: "Check for breathing, keep victim comfortable, clear road access for ambulance.",
      fireTitle: "Fire",
      fireDesc: "Structure fire, forest fire, short circuits or gas leaks",
      fireAction: "Evacuate the premises, cover nose to avoid smoke, close doors behind you.",
      womenTitle: "Women Safety",
      womenDesc: "Harassment, stalking, domestic violence or threatening behavior",
      womenAction: "Seek crowded areas, trigger emergency reporting, look for active police presence.",
      childTitle: "Child Safety",
      childDesc: "Child labor, abuse, child trafficking or missing child report",
      childAction: "Log exact physical descriptions, landmarks, or vehicle license plates.",
      seniorTitle: "Senior Citizen",
      seniorDesc: "Senior welfare check, safety threats or health emergency",
      seniorAction: "Relay pre-existing medical history details if reporting a medical emergency.",
      accidentTitle: "Road Accident",
      accidentDesc: "Traffic collision, vehicle crash, hit-and-run or vehicle blockage",
      accidentAction: "Do not move severely injured victims unless fire or explosion is imminent.",
      disasterTitle: "Disaster",
      disasterDesc: "Flash flood, earthquake, building collapse or industrial hazard",
      disasterAction: "Stay clear of power lines, follow official evacuation orders, keep emergency kit ready.",
      domesticTitle: "Domestic Violence",
      domesticDesc: "Assault, abuse, threat or physical violence within home",
      domesticAction: "Find a secure room, hide phone alerts, submit report as soon as safe.",
      missingTitle: "Missing Person",
      missingDesc: "Adult or minor missing, suspicious disappearance reports",
      missingAction: "Gather recent photographs, clothes worn, last-known GPS coordinates.",
      cyberTitle: "Cyber Crime Guidance",
      cyberDesc: "Phishing, financial theft, harassment or identity theft online",
      cyberAction: "Save screenshots of chats, transactions, URLs, and register report immediately.",
      animalTitle: "Animal Rescue",
      animalDesc: "Injured animals, wild animal intrusion, venomous snake in area",
      animalAction: "Keep eyes on the animal from a safe distance. Do not corner or threaten it.",
    },
    quotes: {
      quote1: "Fear Less. Stand Together. Report Responsibly. Build a Safer India.",
      quote2: "Your Voice Matters. Your Report Can Protect Someone Today.",
      quote3: "Silence Helps Crime. Responsible Reporting Helps Society.",
      quote4: "Every Citizen Has the Power to Protect Their Community.",
      quote5: "Be Alert. Be Responsible. Be the Reason Someone Gets Help.",
      quote6: "Reporting an Incident is an Act of Courage and Civic Responsibility.",
      quote7: "A Safer Society Begins With Responsible Citizens.",
    },
    voiceAgent: {
      successTitle: "Request Sent!",
      successDesc: "Our AI voice agent will call you shortly. The dispatcher has been notified with your location.",
      mobileLabel: "Mobile",
      title: "AI Emergency Voice Agent",
      desc: "Enter your mobile number. Our AI agent will call you and guide you through the emergency. Your location will be shared with the nearest dispatcher.",
      mobileNumber: "Mobile Number",
      mobilePlaceholder: "10-digit mobile number",
      detectingLocation: "Detecting your location…",
      clickToDetect: "Click to detect location",
      connectingDispatcher: "Connecting dispatcher…",
      callMeBtn: "Call Me — Start AI Agent",
      privacyNote: "🔒 Your number and location are shared only with Prakasam Police dispatchers. No data is stored publicly.",
      errorInvalidPhone: "Please enter a valid 10-digit mobile number.",
      errorLocationAccess: "Unable to detect location. Please allow location access.",
      locationNotProvided: "Location not provided",
      errorSubmit: "Failed to connect. Please try again.",
    },
    cta: {
      heading: "Are you witnessing an active emergency?",
      subheading: "Do not hesitate. Your timely report can alert first responders and save lives.",
      btn: "Report Incident Now",
    },
    govAlignment: "National Standards & Legal Compliance",
  },
  te: {
    common: {
      prakasamPolice: "ప్రకాశం పోలీస్",
      citizenPortal: "సిటిజన్ పోర్టల్",
      officialCitizenPortal: "అధికారిక సిటిజన్ పోర్టల్",
      navigation: "నావిగేషన్",
      live: "లైవ్",
      loading: "లోడ్ అవుతోంది...",
      unauthorized: "యాక్సెస్ నిరాకరించబడింది",
      unauthorizedDesc: "ఈ పేజీని యాక్సెస్ చేయడానికి మీకు అనుమతి లేదు.",
      goBack: "వెనుకకు వెళ్ళు",
      submit: "సమర్పించు",
      submitting: "సమర్పిస్తోంది...",
      cancel: "రద్దు చేయి",
      close: "మూసివేయి",
      yes: "అవును",
      no: "కాదు",
    },
    navbar: {
      home: "హోమ్",
      emergencyServices: "అత్యవసర సేవలు",
      knowYourRights: "మీ హక్కులు",
      myPortal: "నా పోర్టల్",
      signIn: "లాగిన్",
      logout: "లాగ్ అవుట్",
      citizen: "పౌరుడు",
      admin: "అడ్మిన్",
      clickToLogout: "లాగ్ అవుట్ చేయడానికి క్లిక్ చేయండి",
      liveConnected: "లైవ్ కనెక్ట్ చేయబడింది",
      disconnected: "డిస్‌కనెక్ట్ చేయబడింది",
      activeEscalations: "క్రియాశీల హెచ్చరికలు",
    },
    hero: {
      heading: "నివేదించడానికి భయపడకండి. మీ స్వరం ప్రాణాలను కాపాడుతుంది.",
      subheading: "ప్రశాంతంగా ఉండండి. ఆందోళన చెందకండి. మీరు ప్రమాదం, నేరం, అగ్ని ప్రమాదం, వైద్య అత్యవసరం లేదా అనుమానాస్పద చర్యను చూసినట్లయితే, భయం లేకుండా సంఘటనను నివేదించండి. మీ సమయానుకూల చర్య ప్రాణాలను రక్షించడంలో, కుటుంబాలను రక్షించడంలో మరియు మన సమాజాన్ని బలోపేతం చేయడంలో సహాయపడుతుంది. ప్రతి బాధ్యతాయుతమైన నివేదిక మన సమాజాన్ని మరింత సురక్షితంగా చేస్తుంది.",
      reportBtn: "సంఘటనను నివేదించండి",
      learnBtn: "ఇది ఎలా పనిచేస్తుందో తెలుసుకోండి",
      quote1: "ప్రతి సెకను ప్రాణాన్ని కాపాడుతుంది.",
      quote2: "సురక్షితమైన రేపటి కోసం అందరం కలిసి.",
      quote3: "మీ భద్రతే మా ప్రాధాన్యత.",
      quote4: "వేగవంతమైన స్పందన. బలమైన రక్షణ.",
      weListen: "మేము వింటాము. మేము స్పందిస్తాము. మేము రక్షిస్తాము.",
    },
    cards: {
      emergencyAssistance: "24×7 అత్యవసర సహాయం",
      emergencyAssistanceDesc: "పోలీసు, అంబులెన్స్ లేదా ఫైర్ విభాగాలకు తక్షణ రూటింగ్.",
      secureReporting: "సురక్షితమైన నివేదిక",
      secureReportingDesc: "మీ సమర్పణలను అత్యంత సురక్షితంగా ఉంచే ఎన్‌క్రిప్టెడ్ కనెక్షన్.",
      quickPoliceResponse: "త్వరిక పోలీసు స్పందన",
      quickPoliceResponseDesc: "సమీపంలోని క్రియాశీల పెట్రోలింగ్ యూనిట్లకు ఆటోమేటిక్ రూటింగ్.",
      trackReport: "మీ గోప్యత ముఖ్యం",
      trackReportDesc: "డిజిటల్ వ్యక్తిగత డేటా రక్షణ చట్టం భద్రతా చర్యలకు అనుగుణంగా ఉంటుంది.",
      aiIncidentAnalysis: "AI సంఘటన విశ్లేషణ",
      aiIncidentAnalysisDesc: "AI అత్యవసర నివేదికలను స్వయంచాలకంగా విశ్లేషిస్తుంది మరియు వేగవంతమైన ప్రతిస్పందన కోసం క్లిష్టమైన సంఘటనలకు ప్రాధాన్యత ఇస్తుంది.",
      liveEmergencyUpdates: "లైవ్ అత్యవసర అప్‌డేట్‌లు",
      liveEmergencyUpdatesDesc: "మీరు నివేదించిన సంఘటనల కోసం నిజ-సమయ నోటిఫिकేషన్‌లు మరియు స్థితి నవీకరణలను స్వీకరించండి.",
    },
    fearSection: {
      heading: "భయం లేకుండా నివేదించండి",
      sub: "అత్యవసర పరిస్థితులను సురక్షితంగా మరియు ధైర్యంగా నివేదించే హక్కు ప్రతి పౌరుడికి ఉంది.",
      card1Title: "మీ గుర్తింపు ముఖ్యం",
      card1Desc: "మీ వ్యక్తిగత సమాచారం సురక్షితంగా నిర్వహించబడుతుంది మరియు చట్టం ప్రకారం అవసరమైనప్పుడు మాత్రమే భాగస్వామ్యం చేయబడుతుంది.",
      card2Title: "ప్రతి నివేదిక విలువైనదే",
      card2Desc: "చిన్న పరిశీలనలు కూడా పెద్ద ప్రమాదాలను నివారించడంలో మరియు ప్రజా భద్రతను మెరుగుపరచడంలో సహాయపడతాయి.",
      card3Title: "మేము మీ గోప్యతను గౌరవిస్తాము",
      card3Desc: "అత్యవసర నివేదికలు తగిన రోల్-ఆధారిత యాక్సెస్ నియంత్రణలతో సురక్షితమైన వ్యవస్థలను ఉపయోగించి ప్రాసెస్ చేయబడతాయి.",
      card4Title: "కలిసి సురక్షితమైన సమాజాలు",
      card4Desc: "త్వరిత నివేదన అత్యవసర సిబ్బంది ప్రజలను వేగంగా చేరుకోవడానికి మరియు బలహీనులను రక్షించడానికి సహాయపడుతుంది.",
    },
    rightsSection: {
      heading: "హక్కులు మరియు బాధ్యతలు తెలుసుకోండి",
      sub: "మీ హక్కులను అర్థం చేసుకోవడం మరియు బాధ్యతాయుతంగా ప్రవర్తించడం ప్రతి ఒక్కరికీ సురక్షితమైన సమాజాన్ని సృష్టించడంలో సహాయపడుతుంది.",
      disclaimer: "గమనిక: ఈ సమాచారం పౌర అవగాహన కోసం మాత్రమే అందించబడింది మరియు అధికారిక చట్టపరమైన సలహా కాదు.",
      item1Title: "అత్యవసర సహాయం హక్కు",
      item1Desc: "భారతదేశపు అత్యవసర ప్రతిస్పందన సేవల ద్వారా అత్యవసర సహాయాన్ని కోరే హక్కు ప్రతి పౌరుడికి ఉంది.",
      item2Title: "సమాచార హక్కు",
      item2Desc: "సమాచార హక్కు చట్టం, 2005 ప్రకారం పౌరులు పబ్లిక్ అథారిటీల నుండి సమాచారాన్ని పొందే హక్కును కలిగి ఉంటారు.",
      item3Title: "గోప్యతా హక్కు",
      item3Desc: "మీ వ్యక్తిగత సమాచారం సురక్షితంగా నిర్వహించబడుతుంది మరియు అత్యవసర స్పందన కోసం మాత్రమే అనుమతించబడిన అధికారులు చూస్తారు.",
      item4Title: "బాధ్యతాయుతమైన నివేదన",
      item4Desc: "ఖచ్చితమైన సమాచారాన్ని అందించడం అత్యవసర సిబ్బంది త్వరగా స్పందించడానికి మరియు సమాజాన్ని రక్షించడానికి సహాయపడుతుంది.",
      item5Title: "డిజిటల్ సాక్ష్యం అవగాహన",
      item5Desc: "సంఘటన సమయంలో సమర్పించిన ఫోటోలు, వీడియోలు, వాయిస్ నోట్స్ మరియు స్థానం దర్యాప్తుకు సహాయపడతాయి.",
      item6Title: "సామాజిక బాధ్యత",
      item6Desc: "అత్యవసర పరిస్థితులను త్వరగా నివేదించడం సురక్షితమైన సమాజానికి మరియు అవసరమైన వారికి వేగవంతమైన సహాయానికి దోహదం చేస్తుంది.",
    },
    login: {
      loginTitle: "ప్రకాశం పోలీస్ పోర్టల్",
      loginSub: "సిటిజన్ పోర్టల్‌ను యాక్సెస్ చేయడానికి వివరాలను నమోదు చేయండి",
      registerTitle: "సిటిజన్ ఖాతాను సృష్టించండి",
      registerSub: "అత్యవసర పరిస్థితులను నివేదించడానికి మరియు ట్రాక్ చేయడానికి సైన్ అప్ చేయండి",
      fullName: "పూర్తి పేరు",
      fullNamePlaceholder: "మీ పూర్తి పేరును నమోదు చేయండి",
      email: "ఈమెయిల్ చిరునామా",
      emailPlaceholder: "name@example.com",
      password: "పాస్‌వర్డ్",
      passwordPlaceholder: "••••••••",
      confirmPassword: "పాస్‌వర్డ్‌ను నిర్ధారించండి",
      confirmPasswordPlaceholder: "••••••••",
      phone: "ఫోన్ నంబర్ (ఐచ్ఛికం)",
      phonePlaceholder: "10 అంకెల మొబైల్ నంబర్‌ను నమోదు చేయండి",
      signInBtn: "పోర్టల్‌కి లాగిన్ అవ్వండి",
      signUpBtn: "సిటిజన్ ఖాతాను సృష్టించండి",
      signingIn: "లాగిన్ అవుతోంది...",
      creatingAccount: "ఖాతాను సృష్టిస్తోంది...",
      needAccount: "ఖాతా లేదా?",
      registerLink: "ఇక్కడ నమోదు చేసుకోండి",
      haveAccount: "ఇప్పటికే ఖాతా ఉందా?",
      loginLink: "ఇక్కడ లాగిన్ అవ్వండి",
      errorDeny: "యాక్సెస్ నిరాకరించబడింది: పౌరులు మాత్రమే ఈ పోర్టల్‌కి లాగిన్ చేయగలరు.",
      errorMatch: "పాస్‌వర్డ్‌లు సరిపోలడం లేదు.",
      errorLength: "పాస్‌వర్డ్ కనీసం 6 అక్షరాలు ఉండాలి.",
      errorRegister: "నమోదు విఫలమైంది. ఈమెయిల్ ఇప్పటికే ఉపయోగంలో ఉండవచ్చు.",
      welcomeBack: "స్వాగతం",
      welcome: "స్వాగతం",
      accountCreated: "ఖాతా సృష్టించబడింది.",
      invalidCreds: "చెల్లని ఈమెయిల్ లేదా పాస్‌వర్డ్. దయచేసి మళ్ళీ ప్రయత్నించండి.",
      quickDemoLogin: "తక్షణ డెమో లాగిన్",
      useDemoAccount: "డెమో సిటిజన్ ఖాతాను ఉపయోగించండి",
      demoPasswordLabel: "డెమో పాస్‌వర్డ్",
      backToHome: "హోమ్‌కి తిరిగి వెళ్ళు",
    },
    portal: {
      reportTitle: "అత్యవసర సంఘటన నివేదిక",
      reportSub: "డిస్పాచర్‌లను అప్రమత్తం చేయడానికి అత్యవసర వివరాలను అందించండి",
      incidentTitleLabel: "సంఘటన శీర్షిక",
      incidentTitlePlaceholder: "అత్యవసర పరిస్థితిని క్లుప్తంగా వివరించండి (ఉదా. హైవే క్రాస్‌రోడ్స్ వద్ద కారు ప్రమాదం)",
      descriptionLabel: "సంఘటన వివరణ",
      descriptionPlaceholder: "స్పందనదారులకు సహాయపడే వివరాలను అందించండి (ఉదా. ఎంతమంది పాల్గొన్నారు, గాయాలు, ప్రమాద తీవ్రత)",
      typeLabel: "సంఘటన వర్గం",
      typePlaceholder: "-- సంఘటన రకాన్ని ఎంచుకోండి --",
      weaponLabel: "ఆయుధం చేర్చబడిందా?",
      peopleLabel: "ప్రభావితమైన వ్యక్తుల అంచనా",
      locationLabel: "సంఘటన జరిగిన స్థలం",
      locationPlaceholder: "మ్యాప్‌లో స్థలాన్ని ఎంచుకోండి లేదా GPS ఉపయోగించండి",
      gpsBtn: "ప్రస్తుత GPS స్థానాన్ని ఉపయోగించండి",
      gpsSearching: "GPS స్థానాన్ని శోధిస్తోంది...",
      gpsError: "GPS ని తిరిగి పొందడం సాధ్యం కాలేదు. దయచేసి మ్యాప్‌లో మాన్యువల్‌గా ఎంచుకోండి.",
      successTitle: "సంఘటన నిвеదిక విజయవంతంగా సమర్పించబడింది! 🚨",
      successDesc: "మీ నివేదిక ప్రకాశం పోలీస్ డిస్పాచ్ ద్వారా స్వీకరించబడింది. ట్రాకింగ్ ప్రారంభమైంది.",
      successNotice: "డిస్పాచర్ సమీక్ష పురోగతిలో ఉంది. మీ ఫోన్ లైన్ అందుబాటులో ఉంచండి.",
      incidentId: "సంఘటన ID",
      assignedUnit: "కేటాయించిన యూనిట్",
      awaitingDispatch: "డిస్పాచ్ కోసం వేచి ఉంది",
      activePatrol: "🚔 యూనిట్",
      priorityLabel: "ప్రాధాన్యత స్థాయి",
      statusLabel: "ప్రస్తుత స్థితి",
      viewDashboard: "సంఘటన డాష్‌బోర్డ్‌కి వెళ్లండి",
      submitIncidentBtn: "అత్యవసర నివేదికను సమర్పించండి",
      validationTitle: "దయచేసి అవసరమైన అన్ని ఫీల్డ్‌లను పూరించండి.",
      validationLocation: "దయచేసి మ్యాప్‌లో స్థానాన్ని ఎంచుకోండి.",
      submitError: "నివేదికను సమర్పించడం విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.",
      fetchingAddress: "చిరునామాను పొందుతోంది...",
      step1: "సంఘటన వివరాలు",
      step2: "స్థాన ధృవీకరణ",
      gpsUnsupported: "మీ బ్రౌజర్ జియోలొకేషన్‌ను సపోర్ట్ చేయదు.",
      gpsCaptured: "GPS స్థానం పొందబడింది",
      gpsDenied: "స్థాన अनुमति నిరాకరించబడింది. దయచేసి సెట్టింగ్లలో అనుమతించండి లేదా మ్యాప్‌లో మాన్యువల్‌గా పిన్ చేయండి.",
      gpsTimeout: "GPS సమయం ముగిసింది. దయచేసి మ్యాప్‌లో మాన్యువల్‌గా పిన్ చేయండి.",
      gpsPinHint: "దయచేసి మ్యాప్‌లో మీ స్థానాన్ని పిన్ చేయండి.",
      incidentSummary: "సంఘటన సారాంశం",
      priorityScore: "ప్రాధాన్యత స్కోరు",
      p1AutoDispatched: "P1 అత్యవసరం — సహాయక బృందం ఆటోమేటిక్‌గా పంపబడింది!",
      reportAnother: "మరొకటి నివేదించండి",
      trackStatus: "స్థితిని ట్రాక్ చేయండి",
      refetchGps: "GPSని మళ్ళీ శోధించండి",
      retryGps: "GPSని తిరిగి ప్రయత్నించండి",
      stepCategory: "సంఘటన రకం",
      stepDescribe: "సంఘటన వివరాలు",
      stepLocation: "స్థానాన్ని పిన్ చేయండి",
      gpsObtaining: "అత్యంత ఖచ్చితమైన GPS కోఆర్డినేట్‌లను పొందుతోంది...",
      emergencyDispatchGrid: "అత్యవసర డిస్పాచ్ గ్రిడ్",
      reportDescText: "మీ నివేదిక స్వయంచాలకంగా జియోకోడ్ చేయబడుతుంది, AI ప్రాధాన్యత ద్వారా వర్గీకరించబడుతుంది మరియు సమీప రెస్పాన్స్ బృందానికి పంపబడుతుంది.",
      gpsInstructions: "మీ పరికరం యొక్క GPS కోఆర్డినేట్‌లు స్వయంచాలకంగా లోడ్ అవుతాయి. పిన్‌ను మార్చడానికి మీరు మ్యాప్‌పై క్లిక్ చేయవచ్చు.",
      btnNextDetails: "తరువాత: వివరాలను వివరించండి →",
      btnNextLocation: "తరువాత: స్థానాన్ని పిన్ చేయండి →",
    },
    myIncidents: {
      myIncidentsTitle: "నా అత్యవసర నివేదికలు",
      incDashboard: "సంఘటన డాష్‌బోర్డ్",
      trackLive: "మీరు సమర్పించిన అత్యవసర నివేదికల లైవ్ డిస్పాచ్ స్థితిని ట్రాక్ చేయండి.",
      failedLoad: "మీ నివేదికలను లోడ్ చేయడం విఫలమైంది",
      noReports: "నివేదికలు నమోదు కాలేదు",
      noReportsDesc: "మీరు ఈ సిటిజన్ ఖాతా నుండి ఇంకా ఎటువంటి అత్యవసర నివేదికలను నమోదు చేయలేదు.",
      assignedUnitLabel: "కేటాయించిన యూనిట్",
      statusLabelCaps: "స్థితి",
      locationLabelCaps: "స్థలం",
    },
    types: {
      assault: "దాడి (Assault)",
      robbery: "దోపిడీ (Robbery)",
      shooting: "కాల్పులు (Shooting)",
      accident: "ప్రమాదం (Accident)",
      fire: "అగ్ని ప్రమాదం (Fire)",
      medical: "వైద్య అత్యవసరం (Medical)",
      domestic_violence: "గృహ హింస (Domestic Violence)",
      theft: "దొంగతనం (Theft)",
      vandalism: "విధ్వంసం (Vandalism)",
      suspicious: "అనుమానాస్పద చర్య (Suspicious)",
      noise: "శబ్ద కాలుష్యం (Noise)",
      other: "ఇతర అత్యవసరం (Other)",
    },
    typesDesc: {
      assault: "వ్యక్తిపై శారీరక దాడి",
      robbery: "బలవంతంగా లేదా బెదిరించి దొంగతనం చేయడం",
      shooting: "తుపాకీ కాల్పులు లేదా గాయాలు",
      accident: "వాహన ప్రమాదం లేదా ఢీకొనడం",
      fire: "భవనం లేదా వాహనం అంటుకోవడం",
      medical: "తక్షణ వైద్య సహాయం",
      domestic_violence: "గృహ వేధింపులు",
      theft: "దొంగిలించబడిన ఆస్తి",
      vandalism: "ఆస్తి నష్టం",
      suspicious: "అనుమానాస్పद కదలికలు",
      noise: "శబ్ద ఆటంకాలు",
      other: "ఇతర అత్యవసర పరిస్థితి",
    },
    status: {
      pending: "పెండింగ్",
      dispatched: "డిస్పాచ్ చేయబడింది",
      en_route: "మార్గంలో ఉంది",
      resolved: "పరిష్కరించబడింది",
    },
    priority: {
      P1: "P1 (అత్యంత క్లిష్టమైనది)",
      P2: "P2 (ఎక్కువ)",
      P3: "P3 (మధ్యస్థం)",
      P4: "P4 (తక్కువ)",
    },
    footer: {
      helplines: "అధికారిక అత్యవసర సేవలు & హెల్ప్‌లైన్లు",
      safetyGuidelines: "పౌర భద్రతా మార్గదర్శకాలు",
      disclaimerText: "ఈ పోర్టల్ కేవలం ప్రజల భద్రత మరియు స్పందన అనుకరణ ప్రదర్శన కోసం అభివృద్ధి చేయబడింది.",
    },
    services: {
      nationalHelpline: "జాతీయ హెల్ప్‌లైన్ (ERSS)",
      nationalHelplineDesc: "అన్ని రకాల సంక్షోభాల కోసం ఏకీకృత అత్యవసర స్పందన వ్యవస్థ",
      policeControl: "పోలీస్ కంట్రోల్ రూమ్",
      policeControlDesc: "రాష్ట్ర పోలీస్ డిస్పాచ్ సెంటర్లకు నేరుగా కనెక్ట్ చేస్తుంది",
      fireRescue: "ఫైర్ & రెస్క్యూ సేవలు",
      fireRescueDesc: "అగ్నిమాపక చర్యలు, ప్రమాద నివారణ మరియు రెస్క్యూ ఆపరేషన్లు",
      medicalAssistance: "అంబులెన్స్ / వైద్య సహాయం",
      medicalAssistanceDesc: "తక్షణ వైద్య రవాణా మరియు అంబులెన్స్ రూటింగ్",
      womenHelpline: "మహిళా హెల్ప్‌లైన్",
      womenHelplineDesc: "వేధింపులు మరియు దుర్వినియోగ కేసుల కోసం భద్రతా మద్దతు",
    },
    safety: {
      tip1Title: "ప్రశాంతంగా ఉండండి మరియు పరిశీలించండి",
      tip1Text: "దీర్ఘ శ్వాస తీసుకోండి. ఏదైనా నివేదికను దాఖలు చేసే ముందు భద్రత కోసం మీ తక్షణ పరిసరాలను పరిశీలించండి.",
      tip2Title: "ఖచ్చితమైన స్థాన వివరాలను పంచుకోండి",
      tip2Text: "మ్యాప్‌లో మీ స్థానాన్ని స్పష్టంగా చూపండి. ల్యాండ్‌మార్క్‌లు లేదా వీధి పేర్లు స్పందనదారులను వేగంగా పంపడానికి సహాయపడతాయి.",
      tip3Title: "డిజిటల్ సాక్ష్యాలను భద్రపరచండి",
      tip3Text: "మీకు ఎటువంటి ప్రమాదం లేనప్పుడు మరియు ఇతరుల దృష్టిని ఆకర్షించకుండా సురక్షితంగా ఉన్నప్పుడే ఫోటోలు తీయండి లేదా వీడియోలను అప్‌లోడ్ చేయండి.",
      tip4Title: "స్పందించే అధికారులకు సహకరించండి",
      tip4Text: "వివరాలను పంచుకోవడానికి సిద్ధంగా ఉండండి. అదనపు వివరాల కోసం డిస్పాచర్లు మీకు తిరిగి కాల్ చేసే అవకాశం ఉన్నందున మీ ఫోన్ లైన్‌ను ఖాళీగా ఉంచండి.",
      tip5Title: "తప్పుడు నివేదికలను నివారించండి",
      tip5Text: "తప్పుడు నివేదికలను దాఖలు చేయడం అసలైన అత్యవసర పరిస్థితులకు సహాయాన్ని ఆలస్యం చేస్తుంది. అన్ని సమర్పణలు నిజమైనవని మరియు సత్యమైనవని నిర్ధారించుకోండి.",
    },
    categories: {
      crimeTitle: "నేరం (Crime)",
      crimeDesc: "దొంగతనం, దాడి, దోపిడీ లేదా క్రియాశీల ఆస్తి ప్రమాదం",
      crimeAction: "ఏదైనా చట్టవిరుద్ధమైన చర్యలను వెంటనే నివేదించండి. నిందితులకు దూరంగా ఉండండి.",
      medicalTitle: "వైద్య అత్యవసరం",
      medicalDesc: "తీవ్రమైన ఆరోగ్య సంక్షోభం, ప్రమాదాలు లేదా అత్యవసర వైద్య రవాణా",
      medicalAction: "అంబులెన్స్ కోసం దారి ఇవ్వండి, బాధితుడికి సౌకర్యంగా ఉండేలా చూడండి.",
      fireTitle: "అగ్ని ప్రమాదం",
      fireDesc: "భవనంలో మంటలు, అడవి మంటలు, షార్ట్ సర్క్యూట్లు లేదా గ్యాస్ లీక్‌లు",
      fireAction: "ఆవరణను ఖాళీ చేయండి, పొగ పీల్చకుండా ముక్కును కప్పుకోండి, తలుపులు మూసివేయండి.",
      womenTitle: "మహిళల రక్షణ",
      womenDesc: "వేధింపులు, వెంబడించడం, గృహ హింస లేదా బెదిరింపు ప్రవర్తన",
      womenAction: "జనసమ్మర్దంగా ఉన్న ప్రాంతాలకు వెళ్ళండి, అత్యవసర నివేదికను పంపండి, పోలీసుల కోసం చూడండి.",
      childTitle: "బాలల రక్షణ",
      childDesc: "బాల కార్మికులు, వేధింపులు, బాలల అక్రమ రవాణా లేదా తప్పిపోయిన పిల్లల నివేదిక",
      childAction: "ఖచ్చితమైన భౌతిక వివరణలు, ల్యాండ్‌మార్క్‌లు లేదా వాహన లైసెన్స్ ప్లేట్లను నమోదు చేయండి.",
      seniorTitle: "వయోవృద్ధుల రక్షణ",
      seniorDesc: "వయోవృద్ధుల సంక్షేమ తనిఖీ, భద్రతా బెదిరింపులు లేదా ఆరోగ్య అత్యవసరం",
      seniorAction: "వైద్య అత్యవసర పరిస్థితిని నివేదిస్తుంటే ముందుగా ఉన్న ఆరోగ్య చరిత్ర వివరాలను తెలియజేయండి.",
      accidentTitle: "రోడ్డు ప్రమాదం",
      accidentDesc: "ట్రాఫిక్ ప్రమాదం, వాహన క్రాష్, హిట్ అండ్ రన్ లేదా వాహన బ్లాకేజ్",
      accidentAction: "అగ్ని లేదా పేలుడు ముప్పు పొంచి ఉంటే తప్ప తీవ్రంగా గాయపడిన బాధితులను తరలించవద్దు.",
      disasterTitle: "విపత్తు (Disaster)",
      disasterDesc: "వరదలు, భూకంపం, భవనం కూలిపోవడం లేదా పారిశ్రామిక ప్రమాదం",
      disasterAction: "విద్యుత్ లైన్లకు దూరంగా ఉండండి, అధికారిక ఖాళీ ఆదేశాలను పాటించండి, అత్యవసర కిట్ సిద్ధంగా ఉంచండి.",
      domesticTitle: "గృహ హింస (Domestic Violence)",
      domesticDesc: "ఇంట్లో దాడి, వేధింపులు, బెదిరింపులు లేదా శారీరక హింస",
      domesticAction: "సురక్షితమైన గదిని కనుగొనండి, ఫోన్ హెచ్చరికలను దాచండి, సురక్షితంగా ఉన్న వెంటనే నివేదించండి.",
      missingTitle: "తప్పిపోయిన వ్యక్తి (Missing Person)",
      missingDesc: "పెద్దలు లేదా మైనర్లు తప్పిపోవడం, అనుమానాస్పదంగా అదృశ్యమవడం నివేదికలు",
      missingAction: "ఇటీవలి ఫోటోగ్రాఫ్‌లు, ధరించిన బట్టలు, చివరిగా తెలిసిన GPS కోఆర్డినేట్‌లను సేకరించండి.",
      cyberTitle: "సైబర్ క్రైమ్ మార్గదర్శకత్వం (Cyber Crime Guidance)",
      cyberDesc: "ఆన్‌లైన్ ఫిషింగ్, ఆర్థిక దొంగతనం, వేధింపులు లేదా గుర్తింపు దొంగతనం",
      cyberAction: "చాట్‌లు, లావాదేవీలు, URLల స్క్రీన్‌షాట్‌లను సేవ్ చేయండి మరియు వెంటనే నివేదికను నమోదు చేయండి.",
      animalTitle: "జంతు రక్షణ (Animal Rescue)",
      animalDesc: "గాయపడిన జంతువులు, అడవి జంతువుల ప్రవేశం, విషసర్పాలు ఉన్నట్లు నివేదికలు",
      animalAction: "సురక్షితమైన దూరం నుండి జంతువుపై నిఘా ఉంచండి. దానిని మూలకు నెట్టడం లేదా బెదిరించడం చేయవద్దు.",
    },
    quotes: {
      quote1: "భయం వీడండి. కలిసి నిలబడండి. బాధ్యతాయుతంగా నివేదించండి. సురక్షితమైన భారతదేశాన్ని నిర్మించండి.",
      quote2: "మీ వాయిస్ ముఖ్యం. మీ నివేదిక ఈరోజు ఒకరిని రక్షించగలదు.",
      quote3: "మౌనం నేరానికి సహాయపడుతుంది. బాధ్యతాయుతమైన నివేదిక సమాజానికి సహాయపడుతుంది.",
      quote4: "ప్రతి పౌరుడికి వారి సమాజాన్ని రక్షించే శక్తి ఉంటుంది.",
      quote5: "అప్రమత్తంగా ఉండండి. బాధ్యతాయుతంగా ఉండండి. ఒకరికి సహాయం అందేలా చేయండి.",
      quote6: "ఒక సంఘటనను నివేదించడం అనేది ధైర్యానికి మరియు పౌర బాధ్యతకు చిహ్నం.",
      quote7: "సురక్షితమైన సమాజం బాధ్యతాయుతమైన పౌరులతోనే ప్రారంభమవుతుంది.",
    },
    voiceAgent: {
      successTitle: "అభ్యర్థన పంపబడింది!",
      successDesc: "మా AI వాయిస్ ఏజెంట్ త్వరలో మీకు కాల్ చేస్తారు. మీ స్థానంతో డిస్పాచర్‌కు సమాచారం ఇవ్వబడింది.",
      mobileLabel: "మొబైల్",
      title: "AI అత్యవసర వాయిస్ ఏజెంట్",
      desc: "మీ మొబైల్ నంబర్‌ను నమోదు చేయండి. మా AI ఏజెంట్ మీకు కాల్ చేసి అత్యవసర పరిస్థితిలో మార్గనిర్దేశం చేస్తారు. మీ స్థానం సమీప డిస్పాచర్‌తో భాగస్వామ్యం చేయబడుతుంది.",
      mobileNumber: "మొబైల్ నంబర్",
      mobilePlaceholder: "10 అంకెల మొబైల్ నంబర్",
      detectingLocation: "మీ స్థానాన్ని గుర్తిస్తోంది...",
      clickToDetect: "స్థానాన్ని గుర్తించడానికి క్లిక్ చేయండి",
      connectingDispatcher: "డిస్పాచర్‌ను కనెక్ట్ చేస్తోంది...",
      callMeBtn: "నాకు కాల్ చేయండి — AI ఏజెంట్ ప్రారంభించండి",
      privacyNote: "🔒 మీ నంబర్ మరియు స్థానం ప్రకాశం పోలీస్ డిస్పాచర్‌లతో మాత్రమే భాగస్వామ్యం చేయబడతాయి. ఏ సమాచారం బహిరంగంగా నిల్వ చేయబడదు.",
      errorInvalidPhone: "దయచేసి చెల్లుబాటు అయ్యే 10 అంకెల మొబైల్ నంబర్‌ను నమోదు చేయండి.",
      errorLocationAccess: "స్థానాన్ని గుర్తించడం సాధ్యం కాలేదు. దయచేసి స్థాన అనుమతిని ఇవ్వండి.",
      locationNotProvided: "స్థానం అందించబడలేదు",
      errorSubmit: "కనెక్ట్ చేయడం విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    },
    cta: {
      heading: "మీరు అత్యవసర పరిస్థితిని చూస్తున్నారా?",
      subheading: "ఆలస్యం చేయకండి. మీ సకాల నివేదిక మొదటి స్పందనదారులను అప్రమత్తం చేస్తుంది.",
      btn: "వెంటనే నివేదించండి",
    },
    govAlignment: "జాతీయ ప్రమాణాలు & చట్టపరమైన సమ్మతి",
  },
  hi: {
    common: {
      prakasamPolice: "प्रकाशम पुलिस",
      citizenPortal: "नागरिक पोर्टल",
      officialCitizenPortal: "आधिकारिक नागरिक पोर्टल",
      navigation: "नेविगेशन",
      live: "लाइव",
      loading: "लोड हो रहा है...",
      unauthorized: "पहुंच अस्वीकृत",
      unauthorizedDesc: "आपको इस पृष्ठ को एक्सेस करने की अनुमति नहीं है।",
      goBack: "वापस जाएं",
      submit: "जमा करें",
      submitting: "जमा किया जा रहा है...",
      cancel: "रद्द करें",
      close: "बंद करें",
      yes: "हाँ",
      no: "नहीं",
    },
    navbar: {
      home: "होम",
      emergencyServices: "आपातकालीन सेवाएं",
      knowYourRights: "अपने अधिकार जानें",
      myPortal: "मेरा पोर्टल",
      signIn: "साइन इन",
      logout: "लॉग आउट",
      citizen: "नागरिक",
      admin: "एडमिन",
      clickToLogout: "लॉग आउट करने के लिए क्लिक करें",
      liveConnected: "लाइव कनेक्टेड",
      disconnected: "डिस्कनेक्टेड",
      activeEscalations: "सक्रिय अलर्ट",
    },
    hero: {
      heading: "रिपोर्ट करने से न डरें। आपकी आवाज़ ज़िंदगियाँ बचा सकती है।",
      subheading: "शांत रहें। घबराएं नहीं। यदि आप किसी दुर्घटना, अपराध, आग, चिकित्सा आपातकाल या संदिग्ध गतिविधि को देखते हैं, तो बिना किसी डर के घटना की रिपोर्ट करें। आपकी सामयिक कार्रवाई से जानें बचाई जा सकती हैं, परिवारों की रक्षा हो सकती है और हमारा समुदाय मजबूत हो सकता है। प्रत्येक जिम्मेदार रिपोर्ट हमारे समाज को सुरक्षित बनाती है।",
      reportBtn: "घटना की रिपोर्ट करें",
      learnBtn: "यह कैसे काम करता है जानें",
      quote1: "हर सेकंड जान बचाता है।",
      quote2: "सुरक्षित कल के लिए एक साथ।",
      quote3: "आपकी सुरक्षा हमारी प्राथमिकता है।",
      quote4: "तेज प्रतिक्रिया। मजबूत सुरक्षा।",
      weListen: "हम सुनते हैं। हम प्रतिक्रिया देते हैं। हम रक्षा करते हैं।",
    },
    cards: {
      emergencyAssistance: "24×7 आपातकालीन सहायता",
      emergencyAssistanceDesc: "पुलिस, एम्बुलेंस, या फायर डिस्पैच के लिए तत्काल मार्ग।",
      secureReporting: "सुरक्षित रिपोर्टिंग",
      secureReportingDesc: "एन्क्रिप्टेड कनेक्शन जो आपकी रिपोर्ट को अत्यंत सुरक्षित रखता है।",
      quickPoliceResponse: "त्वरित पुलिस प्रतिक्रिया",
      quickPoliceResponseDesc: "निकटतम सक्रिय गश्ती इकाइयों के लिए स्वचालित मार्ग।",
      trackReport: "आपकी गोपनीयता महत्वपूर्ण है",
      trackReportDesc: "डिजिटल व्यक्तिगत डेटा संरक्षण अधिनियम के सुरक्षा उपायों के अनुरूप।",
      aiIncidentAnalysis: "AI घटना विश्लेषण",
      aiIncidentAnalysisDesc: "AI स्वचालित रूप से आपातकालीन रिपोर्टों का विश्लेषण करता है और त्वरित प्रतिक्रिया के लिए महत्वपूर्ण घटनाओं को प्राथमिकता देता है।",
      liveEmergencyUpdates: "लाइव आपातकालीन अपडेट",
      liveEmergencyUpdatesDesc: "अपनी रिपोर्ट की गई घटनाओं के लिए वास्तविक समय सूचनाएं और स्थिति अपडेट प्राप्त करें।",
    },
    fearSection: {
      heading: "बिना किसी डर के रिपोर्ट करें",
      sub: "हर नागरिक को आपातकालीन स्थितियों की सुरक्षित और आत्मविश्वास से रिपोर्ट करने का अधिकार है।",
      card1Title: "आपकी पहचान महत्वपूर्ण है",
      card1Desc: "आपकी व्यक्तिगत जानकारी सुरक्षित रूप से संभाली जाती है और कानून द्वारा आवश्यक होने पर ही अधिकृत अधिकारियों के साथ साझा की जाती है।",
      card2Title: "हर रिपोर्ट मायने रखती है",
      card2Desc: "छोटी-छोटी टिप्पणियां भी बड़ी घटनाओं को रोकने और सार्वजनिक सुरक्षा में सुधार करने में मदद कर सकती हैं।",
      card3Title: "हम आपकी गोपनीयता का सम्मान करते हैं",
      card3Desc: "उचित भूमिका-आधारित पहुंच नियंत्रण के साथ सुरक्षित प्रणालियों का उपयोग करके आपातकालीन रिपोर्टों को संसाधित किया जाता है।",
      card4Title: "साथ मिलकर सुरक्षित समुदाय",
      card4Desc: "त्वरित रिपोर्टिंग से आपातकालीन कर्मचारियों को लोगों तक तेजी से पहुंचने और कमजोर लोगों की रक्षा करने में मदद मिलती है।",
    },
    rightsSection: {
      heading: "अधिकार और जिम्मेदारियां जानें",
      sub: "अपने अधिकारों को समझना और जिम्मेदारी से कार्य करना सभी के लिए एक सुरक्षित और अधिक सुरक्षित समुदाय बनाने में मदद करता है।",
      disclaimer: "अस्वीकरण: यह जानकारी केवल नागरिक जागरूकता के लिए प्रदान की गई है और कानूनी सलाह नहीं है।",
      item1Title: "आपातकालीन सहायता का अधिकार",
      item1Desc: "प्रत्येक नागरिक को भारत की आपातकालीन प्रतिक्रिया सेवाओं के माध्यम से आपातकालीन सहायता प्राप्त करने का अधिकार है।",
      item2Title: "सूचना का अधिकार",
      item2Desc: "नागरिकों को सूचना का अधिकार अधिनियम, 2005 के तहत सार्वजनिक प्राधिकरणों से जानकारी प्राप्त करने का अधिकार है।",
      item3Title: "गोपनीयता का अधिकार",
      item3Desc: "आपकी व्यक्तिगत जानकारी सुरक्षित रूप से संभाली जाती है और केवल आपातकालीन प्रतिक्रिया के लिए आवश्यक अधिकृत अधिकारियों द्वारा ही पहुँचा जा सकता है।",
      item4Title: "जिम्मेदार रिपोर्टिंग",
      item4Desc: "सटीक जानकारी प्रदान करने से आपातकालीन कर्मचारियों को तेजी से कार्रवाई करने और समुदाय की रक्षा करने में मदद मिलती है।",
      item5Title: "डिजिटल साक्ष्य जागरूकता",
      item5Desc: "घटना के दौरान प्रस्तुत फोटो, वीडियो, वॉयस रिकॉर्डिंग और स्थान विवरण जांच में सहायता कर सकते हैं।",
      item6Title: "सामुदायिक जिम्मेदारी",
      item6Desc: "आपातकालीन स्थितियों की तुरंत रिपोर्ट करना एक सुरक्षित समाज और जरूरतमंदों के लिए तेजी से सहायता प्रदान करने में योगदान देता है।",
    },
    login: {
      loginTitle: "प्रकाशम पुलिस पोर्टल",
      loginSub: "नागरिक पोर्टल तक पहुंचने के लिए क्रेडेंशियल दर्ज करें",
      registerTitle: "नागरिक खाता बनाएं",
      registerSub: "आपातकालीन रिपोर्ट दर्ज करने और ट्रैक करने के लिए साइन अप करें",
      fullName: "पूरा नाम",
      fullNamePlaceholder: "अपना पूरा नाम दर्ज करें",
      email: "ईमेल पता",
      emailPlaceholder: "name@example.com",
      password: "पासवर्ड",
      passwordPlaceholder: "••••••••",
      confirmPassword: "पासवर्ड की पुष्टि करें",
      confirmPasswordPlaceholder: "••••••••",
      phone: "फ़ोन नंबर (वैकल्पिक)",
      phonePlaceholder: "10-अंकीय मोबाइल नंबर दर्ज करें",
      signInBtn: "पोर्टल में लॉगिन करें",
      signUpBtn: "नागरिक खाता बनाएं",
      signingIn: "लॉगिन किया जा रहा है...",
      creatingAccount: "खाता बनाया जा रहा है...",
      needAccount: "खाता नहीं है?",
      registerLink: "यहाँ पंजीकरण करें",
      haveAccount: "पहले से ही एक खाता है?",
      loginLink: "यहाँ लॉगिन करें",
      errorDeny: "पहुंच अस्वीकृत: केवल नागरिक ही इस पोर्टल पर लॉग इन कर सकते हैं।",
      errorMatch: "पासवर्ड मेल नहीं खाते।",
      errorLength: "पासवर्ड कम से कम 6 वर्णों का होना चाहिए।",
      errorRegister: "पंजीकरण विफल रहा। ईमेल पहले से उपयोग में हो सकता है।",
      welcomeBack: "वापसी पर स्वागत है",
      welcome: "स्वागत है",
      accountCreated: "खाता बन गया।",
      invalidCreds: "अमान्य ईमेल या पासवर्ड। कृपया पुनः प्रयास करें।",
      quickDemoLogin: "त्वरित डेमो लॉगिन",
      useDemoAccount: "डेमो नागरिक खाते का उपयोग करें",
      demoPasswordLabel: "डेमो पासवर्ड",
      backToHome: "होम पर वापस जाएं",
    },
    portal: {
      reportTitle: "आपातकालीन घटना रिपोर्ट",
      reportSub: "डिस्पैचर्स को सचेत करने के लिए आपातकाल का विवरण प्रदान करें",
      incidentTitleLabel: "घटना का शीर्षक",
      incidentTitlePlaceholder: "आपातकाल का संक्षेप में वर्णन करें (जैसे, राजमार्ग चौराहे पर कार दुर्घटना)",
      descriptionLabel: "घटना विवरण",
      descriptionPlaceholder: "कोई भी विवरण प्रदान करें जो उत्तरदाताओं की मदद कर सके (जैसे, शामिल लोगों की संख्या, चोटें, खतरे का स्तर)",
      typeLabel: "घटना श्रेणी",
      typePlaceholder: "-- घटना का प्रकार चुनें --",
      weaponLabel: "क्या हथियार शामिल था?",
      peopleLabel: "प्रभावित लोगों की अनुमानित संख्या",
      locationLabel: "घटना स्थल",
      locationPlaceholder: "मानचित्र पर स्थान चुनें या जीपीएस का उपयोग करें",
      gpsBtn: "वर्तमान जीपीएस स्थान का उपयोग करें",
      gpsSearching: "डिवाइस जीपीएस खोजा जा रहा है...",
      gpsError: "जीपीएस खोजने में असमर्थ। कृपया मानचित्र पर स्थान चुनें।",
      successTitle: "घटना रिपोर्ट सफलतापूर्वक सबमिट की गई! 🚨",
      successDesc: "आपकी रिपोर्ट प्रकाशम पुलिस डिस्पैच द्वारा प्राप्त कर ली गई है। ट्रैकिंग शुरू हो गई है।",
      successNotice: "डिस्पैचर समीक्षा प्रगति पर है। अपनी फोन लाइन खुली रखें।",
      incidentId: "घटना आईडी",
      assignedUnit: "आवंटित यूनिट",
      awaitingDispatch: "डिस्पैच की प्रतीक्षा है",
      activePatrol: "🚔 यूनिट",
      priorityLabel: "प्राथमिकता स्तर",
      statusLabel: "वर्तमान स्थिति",
      viewDashboard: "घटना डैशबोर्ड पर जाएं",
      submitIncidentBtn: "आपातकालीन रिपोर्ट सबमिट करें",
      validationTitle: "कृपया सभी आवश्यक फ़ील्ड भरें।",
      validationLocation: "कृपया मानचित्र पर स्थान चुनें।",
      submitError: "रिपोर्ट सबमिट करने में विफल। कृपया पुनः प्रयास करें।",
      fetchingAddress: "पता खोजा जा रहा है...",
      step1: "घटना का विवरण",
      step2: "स्थान सत्यापन",
      gpsUnsupported: "आपका ब्राउज़र जियोलोकेशन का समर्थन नहीं करता है।",
      gpsCaptured: "जीपीएस स्थान मिल गया",
      gpsDenied: "स्थान अनुमति अस्वीकृत। कृपया सेटिंग में अनुमति दें या मैन्युअल रूप से पिन करें।",
      gpsTimeout: "जीपीएस समय समाप्त। कृपया मैन्युअल रूप से पिन करें।",
      gpsPinHint: "कृपया मानचित्र पर अपना स्थान पिन करें।",
      incidentSummary: "घटना सारांश",
      priorityScore: "प्राथमिकता स्कोर",
      p1AutoDispatched: "P1 गंभीर — प्रतिक्रिया दल स्वचालित रूप से भेजा गया!",
      reportAnother: "दूसरी रिपोर्ट करें",
      trackStatus: "स्थिति ट्रैक करें",
      refetchGps: "जीपीएस पुनः प्राप्त करें",
      retryGps: "जीपीएस पुनः प्रयास करें",
      stepCategory: "घटना का प्रकार",
      stepDescribe: "घटना का विवरण",
      stepLocation: "स्थान पिन करें",
      gpsObtaining: "उच्च-सटीक जीपीएस निर्देशांक प्राप्त किए जा रहे हैं...",
      emergencyDispatchGrid: "आपातकालीन प्रेषण ग्रिड",
      reportDescText: "आपकी रिपोर्ट स्वचालित रूप से जियोकोडेड होगी, एआई प्राथमिकता द्वारा वर्गीकृत होगी, और निकटतम प्रतिक्रिया टीम को भेजी जाएगी।",
      gpsInstructions: "आपके डिवाइस के जीपीएस निर्देशांक स्वचालित रूप से लोड होंगे। आप मानचित्र पर क्लिक करके मैन्युअल रूप से पिन बदल सकते हैं।",
      btnNextDetails: "आगे: विवरण दर्ज करें →",
      btnNextLocation: "आगे: स्थान पिन करें →",
    },
    myIncidents: {
      myIncidentsTitle: "मेरी आपातकालीन रिपोर्ट",
      incDashboard: "घटना डैशबोर्ड",
      trackLive: "अपनी सबमिट की गई आपातकालीन रिपोर्टों की लाइव डिस्पैच स्थिति को ट्रैक करें।",
      failedLoad: "आपकी रिपोर्ट लोड करने में विफल",
      noReports: "कोई रिपोर्ट पंजीकृत नहीं",
      noReportsDesc: "आपने अभी तक इस नागरिक खाते से कोई आपातकालीन रिपोर्ट दर्ज नहीं की है।",
      assignedUnitLabel: "आवंटित यूनिट",
      statusLabelCaps: "स्थिति",
      locationLabelCaps: "स्थान",
    },
    types: {
      assault: "हमला (Assault)",
      robbery: "लूटपाट (Robbery)",
      shooting: "गोलीबारी (Shooting)",
      accident: "दुर्घटना (Accident)",
      fire: "आग लगना (Fire)",
      medical: "चिकित्सा आपातकाल (Medical)",
      domestic_violence: "घरेलू हिंसा (Domestic Violence)",
      theft: "चोरी (Theft)",
      vandalism: "तोड़फोड़ (Vandalism)",
      suspicious: "संदिग्ध गतिविधि (Suspicious)",
      noise: "शोरगुल (Noise)",
      other: "अन्य आपातकाल (Other)",
    },
    typesDesc: {
      assault: "किसी व्यक्ति पर शारीरिक हमला",
      robbery: "बलपूर्वक या धमकी देकर चोरी",
      shooting: "गोलीबारी या बंदूक की गोली से घाव",
      accident: "वाहन दुर्घटना या टक्कर",
      fire: "इमारत या वाहन में आग लगना",
      medical: "तुलनात्मक चिकित्सा सहायता",
      domestic_violence: "घरेलू हिंसा",
      theft: "चोरी की गई संपत्ति",
      vandalism: "संपत्ति को नुकसान",
      suspicious: "संदिग्ध हलचल",
      noise: "शोर अशांति",
      other: "अन्य आपातकालीन स्थिति",
    },
    status: {
      pending: "लंबित",
      dispatched: "भेजा गया",
      en_route: "मार्ग में है",
      resolved: "सुलझाया गया",
    },
    priority: {
      P1: "P1 (गंभीर)",
      P2: "P2 (उच्च)",
      P3: "P3 (मध्यम)",
      P4: "P4 (निम्न)",
    },
    footer: {
      helplines: "आधिकारिक आपातकालीन सेवाएं और हेल्पलाइन",
      safetyGuidelines: "नागरिक सुरक्षा दिशा-निर्देश",
      disclaimerText: "यह पोर्टल केवल सार्वजनिक सुरक्षा प्रेषण सिमुलेशन के तहत प्रदर्शन उद्देश्यों के लिए विकसित किया गया है।",
    },
    services: {
      nationalHelpline: "राष्ट्रीय हेल्पलाइन (ERSS)",
      nationalHelplineDesc: "सभी संकटों के लिए एकीकृत आपातकालीन प्रतिक्रिया प्रणाली",
      policeControl: "पुलिस नियंत्रण कक्ष",
      policeControlDesc: "राज्य पुलिस प्रेषण केंद्रों के लिए सीधा मार्ग",
      fireRescue: "अग्निशमन और बचाव सेवाएं",
      fireRescueDesc: "अग्निशमन, खतरा शमन और बचाव कार्य",
      medicalAssistance: "एम्बुलेंस / चिकित्सा सहायता",
      medicalAssistanceDesc: "तत्काल चिकित्सा परिवहन और एम्बुलेंस मार्ग",
      womenHelpline: "महिला हेल्पलाइन",
      womenHelplineDesc: "उत्पीड़न और दुर्व्यवहार के मामलों के लिए सुरक्षा सहायता",
    },
    safety: {
      tip1Title: "शांत रहें और मूल्यांकन करें",
      tip1Text: "गहरी सांस लें। कोई भी रिपोर्ट दर्ज करने से पहले सुरक्षा के लिए अपने आस-पास के वातावरण का मूल्यांकन करें।",
      tip2Title: "सटीक स्थान विवरण साझा करें",
      tip2Text: "मानचित्र पर अपना स्थान स्पष्ट रूप से इंगित करें। मील के पत्थर या सड़क के नाम प्रेषणकर्ताओं को उत्तरदाताओं को तेजी से भेजने में मदद करते हैं।",
      tip3Title: "डिजिटल साक्ष्य सुरक्षित रखें",
      tip3Text: "केवल तभी फ़ोटो लें या वीडियो अपलोड करें जब आप ध्यान आकर्षित किए बिना या खुद को खतरे में डाले बिना ऐसा सुरक्षित रूप से कर सकें।",
      tip4Title: "प्रतिक्रिया देने वाले अधिकारियों के साथ सहयोग करें",
      tip4Text: "विवरण साझा करने के लिए तैयार रहें। यदि प्रेषणकर्ता अतिरिक्त इनपुट के लिए आपको वापस कॉल करते हैं, तो अपनी फोन लाइन खाली रखें।",
      tip5Title: "झूठी रिपोर्टों से बचें",
      tip5Text: "झूठी रिपोर्ट दर्ज करने से वास्तविक संकटों के लिए सहायता में देरी होती है। सुनिश्चित करें कि सभी प्रस्तुतियाँ प्रामाणिक और सत्य हैं।",
    },
    categories: {
      crimeTitle: "अपराध (Crime)",
      crimeDesc: "चोरी, हमला, डकैती, अतिक्रमण या सक्रिय संपत्ति का खतरा",
      crimeAction: "किसी भी गैरकानूनी गतिविधियों की तुरंत रिपोर्ट करें। संदिग्धों से दूरी बनाए रखें।",
      medicalTitle: "चिकित्सा आपातकाल",
      medicalDesc: "गंभीर स्वास्थ्य संकट, दुर्घटनाएं, या तत्काल चिकित्सा परिवहन",
      medicalAction: "सांस की जांच करें, पीड़ित को आरामदायक रखें, एम्बुलेंस के लिए रास्ता साफ करें।",
      fireTitle: "आग लगना",
      fireDesc: "इमारत की आग, जंगल की आग, शॉर्ट सर्किट या लीक",
      fireAction: "परिसर को खाली करें, धुएं से बचने के लिए नाक ढकें, अपने पीछे दरवाजे बंद करें।",
      womenTitle: "महिला सुरक्षा",
      womenDesc: "उत्पीड़न, पीछा करना, घरेलू हिंसा या धमकी भरा व्यवहार",
      womenAction: "भीड़भाड़ वाले इलाकों की तलाश करें, आपातकालीन रिपोर्टिंग चालू करें, सक्रिय पुलिस उपस्थिति देखें।",
      childTitle: "बाल सुरक्षा",
      childDesc: "बाल श्रम, दुर्व्यवहार, बाल तस्करी या लापता बच्चे की रिपोर्ट",
      childAction: "सटीक शारीरिक विवरण, स्थल चिन्ह, या वाहन लाइसेंस प्लेट दर्ज करें।",
      seniorTitle: "वरिष्ठ नागरिक",
      seniorDesc: "वरिष्ठ कल्याण जांच, सुरक्षा खतरे या स्वास्थ्य आपातकाल",
      seniorAction: "चिकित्सा आपातकाल की रिपोर्ट करते समय पहले से मौजूद चिकित्सा इतिहास का विवरण साझा करें।",
      accidentTitle: "सड़क दुर्घटना",
      accidentDesc: "यातायात टक्कर, वाहन दुर्घटना, हिट-एंड-रन या वाहन का रुकना",
      accidentAction: "गंभीर रूप से घायल पीड़ितों को तब तक न हिलाएं जब तक कि आग या विस्फोट की संभावना न हो।",
    },
    voiceAgent: {
      successTitle: "अनुरोध भेजा गया!",
      successDesc: "हमारा एआई वॉयस एजेंट जल्द ही आपको कॉल करेगा। प्रेषक को आपके स्थान के साथ सूचित कर दिया गया है।",
      mobileLabel: "मोबाइल",
      title: "एआई आपातकालीन वॉयस एजेंट",
      desc: "अपना मोबाइल नंबर दर्ज करें। हमारा एआई एजेंट आपको कॉल करेगा और आपातकाल में आपका मार्गदर्शन करेगा। आपका स्थान निकटतम प्रेषक के साथ साझा किया जाएगा।",
      mobileNumber: "मोबाइल नंबर",
      mobilePlaceholder: "10-अंकीय मोबाइल नंबर",
      detectingLocation: "आपका स्थान पता किया जा रहा है...",
      clickToDetect: "स्थान का पता लगाने के लिए क्लिक करें",
      connectingDispatcher: "प्रेषक को जोड़ा जा रहा है...",
      callMeBtn: "मुझे कॉल करें — एआई एजेंट शुरू करें",
      privacyNote: "🔒 आपका नंबर और स्थान केवल प्रकाशम पुलिस प्रेषकों के साथ साझा किया जाता है। कोई भी डेटा सार्वजनिक रूप से संग्रहीत नहीं किया जाता है।",
      errorInvalidPhone: "कृपया एक वैध 10-अंकीय मोबाइल नंबर दर्ज करें।",
      errorLocationAccess: "स्थान का पता लगाने में असमर्थ। कृपया स्थान पहुंच की अनुमति दें।",
      locationNotProvided: "स्थान प्रदान नहीं किया गया",
      errorSubmit: "कनेक्ट करने में विफल। कृपया पुन: प्रयास करें।",
    },
    cta: {
      heading: "क्या आप किसी सक्रिय आपातकाल को देख रहे हैं?",
      subheading: "संकोच न करें। आपकी समय पर की गई रिपोर्ट प्रथम उत्तरदाताओं को सतर्क कर सकती है।",
      btn: "अभी रिपोर्ट करें",
    },
    govAlignment: "राष्ट्रीय मानक और कानूनी अनुपालन",
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    return localStorage.getItem('lang') || 'en';
  });

  const changeLanguage = (newLang) => {
    localStorage.setItem('lang', newLang);
    setLangState(newLang);
  };

  const t = (key) => {
    const keys = key.split('.');
    let value = TRANSLATIONS[lang];
    for (const k of keys) {
      if (value && value[k] !== undefined) {
        value = value[k];
      } else {
        // Fallback to English
        let fallback = TRANSLATIONS['en'];
        for (const fk of keys) {
          if (fallback && fallback[fk] !== undefined) {
            fallback = fallback[fk];
          } else {
            fallback = key;
            break;
          }
        }
        return fallback;
      }
    }
    return value;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
